baseURL = 'http://xenod.dev/'
defaultContentLanguage = "zh"
languageCode = "zh-CN"
hasCJKLanguage = true
title = '瞎蹦跶的自留地'
theme = ["github.com/glfruit/hananke"] 
#theme = "PaperMod" 
resourceDir = "../resources"

DefaultContentLanguage = "zh"
SectionPagesMenu = "main"
Paginate = 10 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[languages]
  [languages.zh]
    title = "瞎蹦哒的自留地"
    weight = 1
    contentDir = "content"

sectionPagesMenu = 'main'
[menu]
  [[menu.main]]
    name = '首页'
    pageRef = '/'
    weight = 10
  [[menu.main]]
    identifier='posts'
    name = '文章'
    pageRef = '/posts'
    weight = 20
  [[menu.main]]
    name = '分类'
    pageRef = '/categories'
    weight = 30
  [[menu.main]]
    name = '关于'
    pageRef = '/about'
    weight = 40

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  custom_css = ["custom.css"]
  recent_copy = "最新文章"
  text_color = ""
  author = ""
  date_format = ":date_full"
  favicon = ""
  site_logo = ""
  description = "在自己的自留地里随着性地撒欢儿、奔跑和呼喊"
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 3
  show_reading_time = true

[[params.ananke_socials]]
name = "twitter"
url = "https://twitter.com/glfruit"
